import { draft, type PlaceSeed } from "./types";

const c = "hiroshima-city";

/** Hiroshima — 20 drafts. Seed values throughout; verify hours and prices. */
export const hiroshima: PlaceSeed[] = [
  draft({ id: "hir-peace-park", city: c, name: "Peace Memorial Park", nameJa: "平和記念公園", category: "memorial", lat: 34.3925, lon: 132.4525,
    station: "genbaku-domu-mae", walk: 3, tags: ["history"], energy: 0.25, crowd: 0.6, discovery: 0.05, signature: 0.95,
    taste: 30, typical: 75, full: 150,
    crowdNote: "Busy but never noisy. School groups in the morning; quiet after five.",
    tip: "Walk it slowly, north to south: the Dome, the Children's Monument, the Cenotaph, then the museum. Allow the whole morning with the museum. It is free and always open.",
    cost: 0, pairs: ["hir-atomic-dome", "hir-peace-museum", "hir-childrens-monument"], sources: ["hpmmuseum.jp"] }),

  draft({ id: "hir-atomic-dome", city: c, name: "Atomic Bomb Dome", nameJa: "原爆ドーム", category: "memorial", lat: 34.3955, lon: 132.4536,
    station: "genbaku-domu-mae", walk: 1, tags: ["history"], energy: 0.1, crowd: 0.7, discovery: 0.05, signature: 0.95,
    taste: 15, typical: 30, full: 45, window: ["before 08:30", "after 18:00"],
    crowdNote: "Coach groups from nine. At dawn or after dark it is you and the building.",
    tip: "You cannot go in; you walk around it. Come early or at night when it is lit, and stand on the far bank of the river for the view the photographs use.",
    cost: 0, pairs: ["hir-peace-park"], sources: ["wikivoyage"] }),

  draft({ id: "hir-peace-museum", city: c, name: "Peace Memorial Museum", nameJa: "広島平和記念資料館", category: "museum", lat: 34.3915, lon: 132.4530,
    station: "genbaku-domu-mae", walk: 8, tags: ["history"], energy: 0.15, crowd: 0.85, discovery: 0.05, signature: 0.95,
    taste: 60, typical: 100, full: 150, window: ["before 09:00"], opens: "08:30", closes: "18:00",
    crowdNote: "The queue to get in can be an hour by late morning; the exhibits inside are shoulder to shoulder. At 8:30 you walk straight in.",
    tip: "Two hundred yen and the reason to come to Hiroshima. It is hard. Go first thing, before you are tired, and give yourself the rest of the morning to sit by the river afterwards.",
    cost: 200, pairs: ["hir-peace-park"], sources: ["hpmmuseum.jp"] }),

  draft({ id: "hir-childrens-monument", city: c, name: "Children's Peace Monument", nameJa: "原爆の子の像", category: "memorial", lat: 34.3935, lon: 132.4525,
    station: "genbaku-domu-mae", walk: 5, tags: ["history"], energy: 0.05, crowd: 0.6, discovery: 0.1, signature: 0.7,
    taste: 10, typical: 15, full: 30,
    crowdNote: "Groups of children ringing the bell; the glass cases of paper cranes around it.",
    tip: "Sadako Sasaki's statue, and the millions of paper cranes sent every year from schools around the world. Fold one before you come; there is a place to leave it.",
    cost: 0, pairs: ["hir-peace-park"], sources: ["wikivoyage"] }),

  draft({ id: "hir-memorial-hall", city: c, name: "Peace Memorial Hall for the Victims", nameJa: "国立広島原爆死没者追悼平和祈念館", category: "museum", lat: 34.3920, lon: 132.4520,
    station: "genbaku-domu-mae", walk: 6, tags: ["history"], energy: 0.1, crowd: 0.3, discovery: 0.5, signature: 0.6,
    taste: 20, typical: 40, full: 60, opens: "08:30", closes: "18:00",
    crowdNote: "Quiet — most people go to the museum and miss this.",
    tip: "Free, underground, and a different register from the museum: a single circular room and the names. If the museum was too much, this is where to sit.",
    cost: 0, pairs: ["hir-peace-museum"], sources: ["hiro-tsuitokinenkan.go.jp"] }),

  draft({ id: "hir-orizuru-tower", city: c, name: "Orizuru Tower", nameJa: "おりづるタワー", category: "viewpoint", lat: 34.3948, lon: 132.4548,
    station: "genbaku-domu-mae", walk: 2, tags: ["popculture"], energy: 0.1, crowd: 0.4, discovery: 0.3, signature: 0.5,
    taste: 30, typical: 45, full: 75, opens: "10:00", closes: "18:00",
    crowdNote: "Rarely a wait.",
    tip: "The open-air roof looks straight down on the Dome and across to Miyajima on a clear day. Expensive for what it is; the paper-crane wall you fold and drop into is the memorable part. Skip if money is tight.",
    cost: 2200, pairs: ["hir-atomic-dome"], sources: ["orizurutower.jp"] }),

  draft({ id: "hir-castle", city: c, name: "Hiroshima Castle", nameJa: "広島城", category: "castle", lat: 34.4027, lon: 132.4593,
    station: "kamiyacho-nishi", walk: 12, tags: ["history"], energy: 0.3, crowd: 0.4, discovery: 0.3, signature: 0.5,
    taste: 30, typical: 60, full: 90, opens: "09:00", closes: "18:00",
    crowdNote: "Comfortable. Locals walk the moat path; visitors are few.",
    tip: "A 1958 reconstruction — the original was destroyed by the bomb — with a modest museum and a good view from the top. The grounds and moat are free and the better part. Twenty minutes from the Peace Park on foot.",
    cost: 370, pairs: ["hir-gokoku-shrine"], seasons: ["sakura"], sources: ["rijo-castle.jp"] }),

  draft({ id: "hir-gokoku-shrine", city: c, name: "Hiroshima Gokoku Shrine", nameJa: "広島護国神社", category: "shrine", lat: 34.4010, lon: 132.4590,
    station: "kamiyacho-nishi", walk: 12, tags: ["shrines"], energy: 0.1, crowd: 0.3, discovery: 0.5, signature: 0.3,
    taste: 10, typical: 20, full: 30,
    crowdNote: "Quiet except at New Year, when half the city comes.",
    tip: "Inside the castle grounds; the Carp baseball team prays here before each season. Ten minutes on the way to the keep.",
    cost: 0, pairs: ["hir-castle"], sources: ["wikivoyage"] }),

  draft({ id: "hir-shukkeien", city: c, name: "Shukkeien Garden", nameJa: "縮景園", category: "garden", lat: 34.4000, lon: 132.4680,
    station: "shukkeien-mae", walk: 2, tags: ["nature"], energy: 0.2, crowd: 0.3, discovery: 0.5, signature: 0.6,
    taste: 30, typical: 50, full: 80, opens: "09:00", closes: "18:00",
    crowdNote: "Calm. Busiest for the maples in late November and still not crowded.",
    tip: "A 1620 stroll garden, rebuilt after the bomb, with a pond you cross on a rainbow-arched bridge. The best hour of quiet in Hiroshima. The prefectural art museum is next door.",
    cost: 260, seasons: ["koyo", "sakura"], pairs: ["hir-prefectural-art"], sources: ["shukkeien.jp"] }),

  draft({ id: "hir-prefectural-art", city: c, name: "Hiroshima Prefectural Art Museum", nameJa: "広島県立美術館", category: "museum", lat: 34.3997, lon: 132.4672,
    station: "shukkeien-mae", walk: 2, tags: ["art"], energy: 0.1, crowd: 0.2, discovery: 0.5, signature: 0.4,
    taste: 40, typical: 75, full: 120, opens: "09:00", closes: "17:00", closedWeekdays: [1],
    crowdNote: "Quiet.",
    tip: "Closed Mondays. Dalí's 'Dream of Venus' and a strong local collection; the third-floor window frames Shukkeien. A combined ticket with the garden is cheaper.",
    cost: 510, pairs: ["hir-shukkeien"], sources: ["hpam.jp"] }),

  draft({ id: "hir-museum-of-art", city: c, name: "Hiroshima Museum of Art", nameJa: "ひろしま美術館", category: "museum", lat: 34.3990, lon: 132.4600,
    station: "kamiyacho-nishi", walk: 8, tags: ["art"], energy: 0.1, crowd: 0.2, discovery: 0.55, signature: 0.5,
    taste: 40, typical: 75, full: 120, opens: "09:00", closes: "17:00", closedWeekdays: [1],
    crowdNote: "Quiet; a few people per room.",
    tip: "Closed Mondays. A small round building with Monet, Van Gogh, Picasso — bought by a bank as a gift to the city after the war. The best small art museum in western Japan.",
    cost: 1500, pairs: ["hir-castle"], sources: ["hiroshima-museum.jp"] }),

  draft({ id: "hir-hondori", city: c, name: "Hondori", nameJa: "本通", category: "shopping", lat: 34.3930, lon: 132.4595,
    station: "hondori", walk: 1, tags: ["shopping", "food"], energy: 0.2, crowd: 0.6, discovery: 0.2, signature: 0.4,
    taste: 20, typical: 45, full: 90,
    crowdNote: "The city's main covered street; busy after work and at weekends, never a crush.",
    tip: "A kilometre of shops under a roof from the Peace Park to the department stores. Useful for a rainy hour; the okonomiyaki floors of the buildings around it are the reason to come.",
    cost: 0, pairs: ["hir-okonomimura"], sources: ["wikivoyage"] }),

  draft({ id: "hir-okonomimura", city: c, name: "Okonomimura", nameJa: "お好み村", category: "food", lat: 34.3915, lon: 132.4620,
    station: "hatchobori", walk: 5, tags: ["food"], energy: 0.05, crowd: 0.7, discovery: 0.3, signature: 0.7,
    taste: 40, typical: 60, full: 90, opens: "11:00", closes: "22:00",
    crowdNote: "Twenty-five stalls on three floors; at peak hours you wait for a counter seat, then it is fast.",
    tip: "Hiroshima okonomiyaki is layered, not mixed, with noodles inside — a different dish from Osaka's. Pick any stall with a free seat; they are all decent. Cash.",
    cost: 1200, pairs: ["hir-hondori"], sources: ["okonomimura.jp"] }),

  draft({ id: "hir-ekie", city: c, name: "Ekie okonomiyaki floor", nameJa: "エキエ", category: "food", lat: 34.3978, lon: 132.4750,
    station: "hiroshima", walk: 1, tags: ["food"], energy: 0.05, crowd: 0.6, discovery: 0.3, signature: 0.4,
    taste: 30, typical: 45, full: 60, opens: "11:00", closes: "22:00",
    crowdNote: "Queues at lunchtime, quick turnover.",
    tip: "Inside the station: a floor of okonomiyaki counters, good ones, ten metres from the Shinkansen gate. The practical answer when you have forty minutes before a train.",
    cost: 1100, sources: ["wikivoyage"] }),

  draft({ id: "hir-mazda-museum", city: c, name: "Mazda Museum", nameJa: "マツダミュージアム", category: "museum", lat: 34.3690, lon: 132.5000,
    station: null, walk: null, tags: ["popculture", "history"], energy: 0.1, crowd: 0.3, discovery: 0.6, signature: 0.5,
    taste: 60, typical: 90, full: 90, booking: "required", lead: 14, opens: "09:00", closes: "16:00", closedWeekdays: [0, 6],
    crowdNote: "Small guided groups; never crowded.",
    tip: "Weekday guided tours only, booked ahead online; you see the assembly line, which is the point. Twenty minutes from the station on the JR Kure line to Mukainada. For people who like factories.",
    cost: 0, sources: ["mazda.com"] }),

  draft({ id: "hir-mitaki-dera", city: c, name: "Mitaki-dera", nameJa: "三瀧寺", category: "temple", lat: 34.4140, lon: 132.4390,
    station: null, walk: null, tags: ["shrines", "nature"], energy: 0.5, crowd: 0.15, discovery: 0.85, signature: 0.6, physical: 0.5,
    taste: 30, typical: 60, full: 90, opens: "08:00", closes: "17:00",
    crowdNote: "A handful of locals. On November weekends, a few more.",
    tip: "A temple on a wooded hillside with three waterfalls and a pagoda moved here from Wakayama as a memorial. The best maples in Hiroshima and almost nobody knows. Fifteen minutes' walk uphill from Mitaki station.",
    cost: 0, skipIf: ["limited_mobility"], seasons: ["koyo"], sources: ["wikivoyage"] }),

  draft({ id: "hir-hijiyama", city: c, name: "Hijiyama Park", nameJa: "比治山公園", category: "park", lat: 34.3850, lon: 132.4720,
    station: null, walk: null, tags: ["nature", "art"], energy: 0.4, crowd: 0.2, discovery: 0.6, signature: 0.4, physical: 0.4,
    taste: 30, typical: 60, full: 120,
    crowdNote: "Quiet; families at weekends, cherry-blossom picnics in April.",
    tip: "A wooded hill east of the centre with the city's contemporary art museum on top and a view over the delta. A good place to walk off the Peace Park. Fifteen minutes from Hijiyama-shita tram stop, uphill.",
    cost: 0, skipIf: ["limited_mobility"], seasons: ["sakura", "koyo"], pairs: ["hir-mocha"], sources: ["wikivoyage"] }),

  draft({ id: "hir-mocha", city: c, name: "Hiroshima City Museum of Contemporary Art", nameJa: "広島市現代美術館", category: "museum", lat: 34.3845, lon: 132.4735,
    station: null, walk: null, tags: ["art"], energy: 0.15, crowd: 0.2, discovery: 0.6, signature: 0.4,
    taste: 40, typical: 75, full: 120, opens: "10:00", closes: "17:00", closedWeekdays: [1],
    crowdNote: "Quiet.",
    tip: "Closed Mondays. Reopened 2023 after renovation, on top of Hijiyama; a strong collection on the theme of the city. Kurokawa's building is half the reason.",
    cost: 400, pairs: ["hir-hijiyama"], sources: ["hiroshima-moca.jp"] }),

  draft({ id: "hir-fudoin", city: c, name: "Fudoin", nameJa: "不動院", category: "temple", lat: 34.4270, lon: 132.4750,
    station: null, walk: null, tags: ["shrines", "history"], energy: 0.15, crowd: 0.1, discovery: 0.9, signature: 0.5,
    taste: 15, typical: 30, full: 45, opens: "09:00", closes: "17:00",
    crowdNote: "Empty.",
    tip: "The only National Treasure building in Hiroshima that survived the bomb — a 1540 hall four kilometres from the hypocentre. Nobody comes. Astram line to Fudoin-mae, two minutes.",
    cost: 0, sources: ["wikivoyage"] }),

  draft({ id: "hir-toshogu", city: c, name: "Hiroshima Toshogu", nameJa: "広島東照宮", category: "shrine", lat: 34.4045, lon: 132.4770,
    station: "hiroshima", walk: 10, tags: ["shrines"], energy: 0.3, crowd: 0.15, discovery: 0.7, signature: 0.4, physical: 0.3,
    taste: 15, typical: 30, full: 45,
    crowdNote: "Empty apart from local walkers.",
    tip: "Up a long staircase behind the station, with a view back over the city and a shrine that survived 1945 with its gate intact. Ten minutes from the Shinkansen — a good use of a spare half hour.",
    cost: 0, sources: ["wikivoyage"] }),

  draft({ id: "hir-kagura", city: c, name: "Hiroshima Kagura night", nameJa: "広島神楽定期公演", category: "performance", lat: 34.3940, lon: 132.4580,
    station: "kamiyacho-nishi", walk: 3, tags: ["history", "offbeat"], energy: 0.05, crowd: 0.4, discovery: 0.7, signature: 0.6,
    taste: 60, typical: 75, full: 90, window: ["after 17:30"], opens: "19:00", closes: "20:30", closedWeekdays: [0, 1, 2, 4, 5, 6],
    crowdNote: "A few hundred seats and rarely full on an ordinary Wednesday.",
    tip: "Every Wednesday evening at the Prefectural Culture Centre: masked, drum-driven mythological dance from the mountain villages — a hero, a serpent, a great deal of smoke. Hiroshima's own tradition and the best-value ticket in the city. English synopsis on the sheet.",
    cost: 1200, booking: "recommended", lead: 7, sources: ["hiroshima-kankou.com"] }),

  draft({ id: "hir-nagarekawa", city: c, name: "Nagarekawa", nameJa: "流川", category: "district", lat: 34.3905, lon: 132.4665,
    station: "hatchobori", walk: 5, tags: ["nightlife", "food"], energy: 0.15, crowd: 0.6, discovery: 0.3, signature: 0.5,
    taste: 30, typical: 90, full: 180, window: ["after 17:30"],
    crowdNote: "Quiet until eight, then busy until late; Friday and Saturday are the loud nights.",
    tip: "The bar district: several hundred small places across a few blocks, most of them a counter and ten stools. Grilled oysters and local sake are the order. Pick a door with a handwritten menu and go in.",
    cost: 0, pairs: ["hir-okonomimura"], sources: ["wikivoyage"] }),

  draft({ id: "hir-carp-game", city: c, name: "Carp game at Mazda Stadium", nameJa: "マツダスタジアム", category: "sport", lat: 34.3925, lon: 132.4845,
    station: "hiroshima", walk: 10, tags: ["popculture"], energy: 0.15, crowd: 0.8, discovery: 0.4, signature: 0.6,
    taste: 90, typical: 180, full: 240,
    crowdNote: "Sells out most weekends; weeknight games are easier and the atmosphere is the same.",
    tip: "Hiroshima's baseball team has the loudest, most coordinated fans in Japan, and a home game is the best evening the city has from late March to early October. Buy online ahead — the cheap outfield seats are the fun ones. Ten minutes' walk from the station along a road painted red.",
    cost: 2500, booking: "required", lead: 30, sources: ["carp.co.jp"] }),

  draft({ id: "hir-ogonzan", city: c, name: "Mount Ogonzan", nameJa: "黄金山", category: "viewpoint", lat: 34.3745, lon: 132.4885,
    station: null, walk: null, tags: ["nature"], energy: 0.5, crowd: 0.1, discovery: 0.9, signature: 0.4, physical: 0.5,
    taste: 30, typical: 60, full: 90, window: ["after 17:30"],
    crowdNote: "Couples in parked cars at night; otherwise nobody.",
    tip: "A 220-metre hill south-east of the centre with the city's night view: the whole delta, the port, and the Inland Sea islands. A steep forty-minute walk up from the bottom, or a taxi to the top. Bring the walk down for the lights.",
    cost: 0, skipIf: ["limited_mobility"], sources: ["wikivoyage"] }),

  draft({ id: "hir-botanical-garden", city: c, name: "Hiroshima Botanical Garden", nameJa: "広島市植物公園", category: "garden", lat: 34.3720, lon: 132.3970,
    station: null, walk: null, tags: ["nature"], energy: 0.3, crowd: 0.2, discovery: 0.7, signature: 0.3,
    taste: 45, typical: 90, full: 150, opens: "09:00", closes: "16:30", closedWeekdays: [5],
    crowdNote: "Families at weekends; near-empty on weekdays.",
    tip: "Closed Fridays. A large hillside garden with a good greenhouse, half an hour west of the centre by JR to Itsukaichi and a bus up. A rainy-day or with-children option, not a must; the cherry avenue is real in early April.",
    cost: 510, seasons: ["sakura"], sources: ["hiroshima-bot.jp"] }),
];
