import { draft, type PlaceSeed } from "./types";

const c = "kyoto-city";

/** Kyoto — 42 drafts. Seed values throughout; verify hours and prices. */
export const kyoto: PlaceSeed[] = [
  draft({ id: "kyt-fushimi-inari", city: c, name: "Fushimi Inari Taisha", nameJa: "伏見稲荷大社", category: "shrine", lat: 34.9671, lon: 135.7727,
    station: "inari", walk: 2, tags: ["shrines", "nature"], energy: 0.45, crowd: 0.9, discovery: 0.1, signature: 0.95, physical: 0.5,
    taste: 45, typical: 90, full: 180, window: ["before 08:00", "after 17:30"],
    crowdNote: "10:00–16:00 the first 300 gates are a shuffling queue. Past the Yotsutsuji viewpoint it empties out almost entirely.",
    worthIf: ["early_riser", "photography"], skipIf: ["limited_mobility", "packed_schedule"],
    tip: "Open 24 hours and unstaffed at night — the 6am visit is the one people remember. Take the Local from Kyoto Station; the Rapid does not stop at Inari.",
    cost: 0, conflicts: ["kyt-arashiyama-bamboo"], pairs: ["kyt-tofukuji"], sources: ["inari.jp"] }),

  draft({ id: "kyt-kiyomizu", city: c, name: "Kiyomizu-dera", nameJa: "清水寺", category: "temple", lat: 34.9949, lon: 135.7850,
    station: "kiyomizu-gojo", walk: 20, tags: ["shrines", "history"], energy: 0.5, crowd: 0.95, discovery: 0.05, signature: 0.95, physical: 0.5,
    taste: 45, typical: 90, full: 120, window: ["before 08:00"], opens: "06:00", closes: "18:00",
    crowdNote: "By ten the approach lanes are a slow river of people. At six it is yours, and the wooden stage catches the morning light.",
    worthIf: ["photography", "history"], skipIf: ["limited_mobility"],
    tip: "The uphill walk from the station is the point as much as the temple — Ninenzaka and Sannenzaka are on the way down. Autumn evening illuminations need a separate ticket.",
    cost: 500, pairs: ["kyt-ninenzaka"], seasons: ["koyo", "sakura"], sources: ["kiyomizudera.or.jp"] }),

  draft({ id: "kyt-ninenzaka", city: c, name: "Ninenzaka & Sannenzaka", nameJa: "二年坂・三年坂", category: "street", lat: 34.9975, lon: 135.7810,
    station: "kiyomizu-gojo", walk: 15, tags: ["history", "shopping"], energy: 0.3, crowd: 0.8, discovery: 0.2, signature: 0.6,
    taste: 30, typical: 75, full: 120,
    crowdNote: "Busy from mid-morning; empties after the shops shut around six, when it is at its most beautiful.",
    tip: "No ticket, no hours — this is the slack in a Higashiyama day. Run it long or cut it short. The Starbucks in a machiya is genuinely worth a look.",
    cost: 0, pairs: ["kyt-kiyomizu", "kyt-kodaiji"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-kodaiji", city: c, name: "Kodai-ji", nameJa: "高台寺", category: "temple", lat: 35.0007, lon: 135.7810,
    station: "kiyomizu-gojo", walk: 15, tags: ["shrines", "nature"], energy: 0.3, crowd: 0.5, discovery: 0.4, signature: 0.6,
    taste: 30, typical: 60, full: 90, opens: "09:00", closes: "17:30",
    crowdNote: "Comfortable even at midday. The autumn night illumination is the exception — queues form.",
    tip: "Two minutes off Ninenzaka and most people walk past it. The bamboo grove at the back is small but empty, unlike the famous one.",
    cost: 600, seasons: ["koyo"], pairs: ["kyt-ninenzaka"], sources: ["kodaiji.com"] }),

  draft({ id: "kyt-yasaka-shrine", city: c, name: "Yasaka Shrine", nameJa: "八坂神社", category: "shrine", lat: 35.0037, lon: 135.7787,
    station: "gion-shijo", walk: 5, tags: ["shrines"], energy: 0.15, crowd: 0.7, discovery: 0.1, signature: 0.6,
    taste: 15, typical: 30, full: 45,
    crowdNote: "Always people, never a queue — it is a thoroughfare as much as a shrine.",
    tip: "Open all night and lit by lanterns after dark; walk through it on the way to or from Gion rather than making a trip of it.",
    cost: 0, pairs: ["kyt-maruyama-park", "kyt-gion"], sources: ["yasaka-jinja.or.jp"] }),

  draft({ id: "kyt-gion", city: c, name: "Gion — Hanamikoji", nameJa: "祇園 花見小路", category: "district", lat: 35.0030, lon: 135.7750,
    station: "gion-shijo", walk: 4, tags: ["history", "nightlife"], energy: 0.2, crowd: 0.85, discovery: 0.15, signature: 0.7,
    taste: 20, typical: 45, full: 90, window: ["after 17:30"],
    crowdNote: "Tour groups fill Hanamikoji by day. Dusk is when it looks like the photographs, and when geiko actually walk to appointments.",
    tip: "Photographing geiko on private lanes is now fined — stay on Hanamikoji itself and keep the camera down when one passes. Shirakawa, two streets north, is prettier and quieter.",
    cost: 0, pairs: ["kyt-yasaka-shrine", "kyt-pontocho"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-maruyama-park", city: c, name: "Maruyama Park", nameJa: "円山公園", category: "park", lat: 35.0035, lon: 135.7815,
    station: "gion-shijo", walk: 8, tags: ["nature"], energy: 0.15, crowd: 0.4, discovery: 0.3, signature: 0.4,
    taste: 15, typical: 30, full: 60,
    crowdNote: "Quiet outside cherry-blossom season, when the weeping cherry draws the whole city at night.",
    tip: "The path from here up to Chion-in and Shoren-in is the calm way north through Higashiyama.",
    cost: 0, seasons: ["sakura"], pairs: ["kyt-yasaka-shrine", "kyt-chionin"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-chionin", city: c, name: "Chion-in", nameJa: "知恩院", category: "temple", lat: 35.0055, lon: 135.7825,
    station: "higashiyama", walk: 10, tags: ["shrines", "history"], energy: 0.4, crowd: 0.4, discovery: 0.4, signature: 0.6, physical: 0.4,
    taste: 30, typical: 60, full: 90, opens: "09:00", closes: "16:30",
    crowdNote: "Rarely crowded — the scale of the place absorbs people.",
    tip: "The Sanmon gate is the largest wooden gate in Japan and free to stand under. The steep stairs behind it are the reason to come.",
    cost: 500, skipIf: ["limited_mobility"], pairs: ["kyt-maruyama-park", "kyt-shorenin"], sources: ["chion-in.or.jp"] }),

  draft({ id: "kyt-shorenin", city: c, name: "Shoren-in", nameJa: "青蓮院", category: "temple", lat: 35.0075, lon: 135.7830,
    station: "higashiyama", walk: 6, tags: ["shrines", "nature"], energy: 0.2, crowd: 0.2, discovery: 0.65, signature: 0.5,
    taste: 30, typical: 45, full: 60, opens: "09:00", closes: "17:00",
    crowdNote: "Nearly empty most days. Sit on the veranda and nobody hurries you.",
    tip: "Two minutes from Chion-in and a fraction of the visitors. The camphor trees outside are older than the temple.",
    cost: 600, seasons: ["koyo"], pairs: ["kyt-chionin"], sources: ["shorenin.com"] }),

  draft({ id: "kyt-heian-shrine", city: c, name: "Heian Shrine", nameJa: "平安神宮", category: "shrine", lat: 35.0161, lon: 135.7823,
    station: "higashiyama", walk: 10, tags: ["shrines", "nature"], energy: 0.2, crowd: 0.5, discovery: 0.3, signature: 0.5,
    taste: 20, typical: 50, full: 80, opens: "06:00", closes: "17:30",
    crowdNote: "The courtyard is wide enough never to feel full. The garden behind it is where the time goes.",
    tip: "The shrine is free; the garden costs and is the better half — weeping cherries in April, a pond you cross on stepping stones.",
    cost: 600, seasons: ["sakura"], sources: ["heianjingu.or.jp"] }),

  draft({ id: "kyt-nanzenji", city: c, name: "Nanzen-ji", nameJa: "南禅寺", category: "temple", lat: 35.0113, lon: 135.7935,
    station: "keage", walk: 8, tags: ["shrines", "history"], energy: 0.3, crowd: 0.5, discovery: 0.3, signature: 0.7,
    taste: 30, typical: 60, full: 100, opens: "08:40", closes: "17:00",
    crowdNote: "The grounds are free and roomy. The Hojo garden and the gate top are ticketed and calmer.",
    tip: "The brick aqueduct in the grounds looks like it wandered in from Rome. Follow it uphill for five minutes to Nanzen-in, which almost nobody does.",
    cost: 600, seasons: ["koyo"], pairs: ["kyt-eikando", "kyt-philosophers-path"], sources: ["nanzenji.or.jp"] }),

  draft({ id: "kyt-eikando", city: c, name: "Eikan-do", nameJa: "永観堂", category: "temple", lat: 35.0148, lon: 135.7945,
    station: "keage", walk: 15, tags: ["shrines", "nature"], energy: 0.35, crowd: 0.6, discovery: 0.4, signature: 0.6,
    taste: 30, typical: 60, full: 90, opens: "09:00", closes: "17:00",
    crowdNote: "Quiet most of the year; in the last three weeks of November it is the most visited maple temple in Kyoto and the price doubles.",
    tip: "Come for the maples or not at all — it is the reason the temple is famous. The Amida statue looking back over its shoulder is the other.",
    cost: 600, seasons: ["koyo"], pairs: ["kyt-nanzenji"], sources: ["eikando.or.jp"] }),

  draft({ id: "kyt-philosophers-path", city: c, name: "Philosopher's Path", nameJa: "哲学の道", category: "street", lat: 35.0210, lon: 135.7950,
    station: "keage", walk: 12, tags: ["nature"], energy: 0.35, crowd: 0.5, discovery: 0.2, signature: 0.6,
    taste: 25, typical: 45, full: 75,
    crowdNote: "A cherry-blossom week apart, it is a stroll not a crush. Cafés along it are the reason it takes longer than it looks.",
    tip: "Walk it north from Nanzen-ji to Ginkaku-ji so you finish at a temple, not a bus stop. Two kilometres, flat, canal-side.",
    cost: 0, seasons: ["sakura", "koyo"], pairs: ["kyt-nanzenji", "kyt-ginkakuji"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-ginkakuji", city: c, name: "Ginkaku-ji", nameJa: "銀閣寺", category: "temple", lat: 35.0270, lon: 135.7982,
    station: "ginkakuji-michi", walk: 8, tags: ["shrines", "nature"], energy: 0.35, crowd: 0.6, discovery: 0.3, signature: 0.7,
    taste: 30, typical: 60, full: 80, opens: "08:30", closes: "17:00",
    crowdNote: "A one-way path, so it moves. Mid-afternoon it slows to a shuffle at the sand garden.",
    tip: "Not silver, never was. The moss garden and the hill path above it are the reason it is better than Kinkaku-ji, whatever the postcards say.",
    cost: 500, seasons: ["koyo"], pairs: ["kyt-philosophers-path", "kyt-honen-in"], sources: ["shokoku-ji.jp"] }),

  draft({ id: "kyt-honen-in", city: c, name: "Honen-in", nameJa: "法然院", category: "temple", lat: 35.0235, lon: 135.7970,
    station: "ginkakuji-michi", walk: 10, tags: ["shrines", "nature"], energy: 0.25, crowd: 0.1, discovery: 0.85, signature: 0.4,
    taste: 15, typical: 30, full: 45, opens: "06:00", closes: "16:00",
    crowdNote: "Often nobody at all. A thatched gate, two raked sand mounds, moss.",
    tip: "Three minutes off the Philosopher's Path and the calmest place on it. The grounds are free; the hall opens only a few weeks a year.",
    cost: 0, seasons: ["koyo"], pairs: ["kyt-ginkakuji"], sources: ["honen-in.jp"] }),

  draft({ id: "kyt-tofukuji", city: c, name: "Tofuku-ji", nameJa: "東福寺", category: "temple", lat: 34.9764, lon: 135.7735,
    station: "tofukuji", walk: 10, tags: ["shrines", "nature"], energy: 0.3, crowd: 0.7, discovery: 0.3, signature: 0.6,
    taste: 30, typical: 60, full: 90, window: ["before 09:30"], opens: "09:00", closes: "16:00",
    crowdNote: "Empty eleven months a year. In late November the Tsutenkyo bridge is shoulder to shoulder by ten and photography is banned on it.",
    tip: "One stop from Kyoto Station on the way to Fushimi Inari — do them together. The Hojo garden's checkerboard moss is modern and better than it sounds.",
    cost: 600, seasons: ["koyo"], pairs: ["kyt-fushimi-inari"], sources: ["tofukuji.jp"] }),

  draft({ id: "kyt-sanjusangendo", city: c, name: "Sanjusangen-do", nameJa: "三十三間堂", category: "temple", lat: 34.9878, lon: 135.7717,
    station: "shichijo", walk: 7, tags: ["shrines", "history", "art"], energy: 0.1, crowd: 0.4, discovery: 0.3, signature: 0.7,
    taste: 30, typical: 50, full: 70, opens: "08:30", closes: "17:00",
    crowdNote: "Steady but never packed — the hall is 120 metres long and people spread out.",
    tip: "1,001 gilded statues in one hall and no photographs allowed, which is why people walk it faster than they expect. Indoors: a good rain day.",
    cost: 600, pairs: ["kyt-national-museum"], sources: ["sanjusangendo.jp"] }),

  draft({ id: "kyt-national-museum", city: c, name: "Kyoto National Museum", nameJa: "京都国立博物館", category: "museum", lat: 34.9900, lon: 135.7730,
    station: "shichijo", walk: 7, tags: ["art", "history"], energy: 0.1, crowd: 0.3, discovery: 0.4, signature: 0.4,
    taste: 45, typical: 90, full: 150, opens: "09:30", closes: "17:00", closedWeekdays: [1],
    crowdNote: "Quiet except during a headline special exhibition, when it is the busiest building in the city.",
    tip: "Closed Mondays, like most museums here. Across the road from Sanjusangen-do — pair them on a wet afternoon.",
    cost: 700, pairs: ["kyt-sanjusangendo"], sources: ["kyohaku.go.jp"] }),

  draft({ id: "kyt-toji", city: c, name: "To-ji", nameJa: "東寺", category: "temple", lat: 34.9807, lon: 135.7475,
    station: "kyoto", walk: 15, tags: ["shrines", "history"], energy: 0.2, crowd: 0.4, discovery: 0.4, signature: 0.6,
    taste: 25, typical: 50, full: 80, opens: "08:00", closes: "17:00",
    crowdNote: "Calm, except on the 21st of each month when the flea market takes over the grounds.",
    tip: "The tallest wooden pagoda in Japan, fifteen minutes' walk from the station — a good first or last thing in Kyoto. The 21st market is worth planning around.",
    cost: 500, seasons: ["koyo"], sources: ["toji.or.jp"] }),

  draft({ id: "kyt-nishi-honganji", city: c, name: "Nishi Hongan-ji", nameJa: "西本願寺", category: "temple", lat: 34.9922, lon: 135.7515,
    station: "kyoto", walk: 12, tags: ["shrines", "history"], energy: 0.15, crowd: 0.2, discovery: 0.6, signature: 0.5,
    taste: 20, typical: 40, full: 60, opens: "05:30", closes: "17:00",
    crowdNote: "A working temple, so it is locals praying rather than visitors looking. Never full.",
    tip: "Free, vast, and ten minutes from the station. Take your shoes off and sit at the back of the main hall for ten minutes — that is the whole visit.",
    cost: 0, sources: ["hongwanji.kyoto"] }),

  draft({ id: "kyt-nishiki-market", city: c, name: "Nishiki Market", nameJa: "錦市場", category: "market", lat: 35.0050, lon: 135.7640,
    station: "shijo", walk: 5, tags: ["food", "shopping"], energy: 0.2, crowd: 0.85, discovery: 0.2, signature: 0.6,
    taste: 30, typical: 60, full: 90, window: ["before 11:00"], opens: "10:00", closes: "18:00",
    crowdNote: "One narrow street, five blocks, and by noon you move at the pace of the slowest person in it.",
    tip: "Eat as you go; most stalls now ask you not to walk while eating, so step to the side. Many close by five and some are shut on Wednesdays.",
    cost: 0, pairs: ["kyt-pontocho"], sources: ["kyoto-nishiki.or.jp"] }),

  draft({ id: "kyt-pontocho", city: c, name: "Pontocho", nameJa: "先斗町", category: "street", lat: 35.0060, lon: 135.7710,
    station: "sanjo", walk: 4, tags: ["food", "nightlife"], energy: 0.15, crowd: 0.7, discovery: 0.3, signature: 0.6,
    taste: 15, typical: 45, full: 120, window: ["after 17:30"],
    crowdNote: "Dead by day. From dusk it is the prettiest lane in the city and every restaurant is full by eight.",
    tip: "An alley of restaurants along the river; in summer many have riverside decks. Book anything with a deck. For a drink without a booking, the bars at the north end.",
    cost: 0, pairs: ["kyt-nishiki-market", "kyt-gion"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-kamogawa", city: c, name: "Kamo River banks", nameJa: "鴨川", category: "park", lat: 35.0090, lon: 135.7720,
    station: "sanjo", walk: 2, tags: ["nature"], energy: 0.2, crowd: 0.3, discovery: 0.3, signature: 0.5,
    taste: 15, typical: 30, full: 60,
    crowdNote: "Couples spaced out along the bank at even intervals, famously. Never crowded.",
    tip: "Free, always open, and the best place in Kyoto to do nothing. Buy something at a konbini and sit between Sanjo and Shijo at dusk.",
    cost: 0, pairs: ["kyt-pontocho"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-nijo-castle", city: c, name: "Nijo Castle", nameJa: "二条城", category: "castle", lat: 35.0142, lon: 135.7481,
    station: "nijojo-mae", walk: 3, tags: ["history"], energy: 0.3, crowd: 0.6, discovery: 0.2, signature: 0.7,
    taste: 45, typical: 90, full: 120, opens: "08:45", closes: "16:00",
    crowdNote: "The Ninomaru palace is a one-way corridor and moves at the group in front. Mornings are noticeably better.",
    tip: "The nightingale floors squeak on purpose. Ninomaru is the point; the gardens are pleasant and the outer grounds can be skipped if time is short.",
    cost: 1300, seasons: ["sakura"], sources: ["nijo-jocastle.city.kyoto.lg.jp"] }),

  draft({ id: "kyt-imperial-palace", city: c, name: "Kyoto Imperial Palace", nameJa: "京都御所", category: "palace", lat: 35.0254, lon: 135.7621,
    station: "imadegawa", walk: 8, tags: ["history"], energy: 0.3, crowd: 0.3, discovery: 0.4, signature: 0.5,
    taste: 30, typical: 60, full: 90, opens: "09:00", closes: "16:00", closedWeekdays: [1],
    crowdNote: "Free entry since 2016 and still uncrowded — the park around it is enormous.",
    tip: "Closed Mondays. You see courtyards and façades, not interiors; the surrounding park is the better reason to come, especially with plum blossom in February.",
    cost: 0, sources: ["sankan.kunaicho.go.jp"] }),

  draft({ id: "kyt-shimogamo", city: c, name: "Shimogamo Shrine", nameJa: "下鴨神社", category: "shrine", lat: 35.0393, lon: 135.7727,
    station: "demachiyanagi", walk: 10, tags: ["shrines", "nature"], energy: 0.25, crowd: 0.3, discovery: 0.55, signature: 0.5,
    taste: 20, typical: 45, full: 70, opens: "06:30", closes: "17:00",
    crowdNote: "Quiet. The approach through Tadasu forest is the quietest walk in central Kyoto.",
    tip: "Older than the city, and the forest around it is a scrap of what was here before Kyoto was. Combine with Demachiyanagi's bakeries on the way.",
    cost: 0, sources: ["shimogamo-jinja.or.jp"] }),

  draft({ id: "kyt-daitokuji", city: c, name: "Daitoku-ji", nameJa: "大徳寺", category: "temple", lat: 35.0437, lon: 135.7462,
    station: "kitaoji", walk: 15, tags: ["shrines", "history"], energy: 0.3, crowd: 0.2, discovery: 0.7, signature: 0.5,
    taste: 30, typical: 75, full: 120, opens: "09:00", closes: "16:30",
    crowdNote: "A walled town of sub-temples, most closed to the public, the open ones almost empty.",
    tip: "Daisen-in and Koto-in are the ones to pay for — dry gardens with nobody in them. This is the Kyoto that the tour buses miss entirely.",
    cost: 500, seasons: ["koyo"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-kinkakuji", city: c, name: "Kinkaku-ji", nameJa: "金閣寺", category: "temple", lat: 35.0394, lon: 135.7292,
    station: "kinkakuji-michi", walk: 5, tags: ["shrines", "history"], energy: 0.2, crowd: 0.9, discovery: 0.05, signature: 0.85,
    taste: 30, typical: 45, full: 60, window: ["before 09:30"], opens: "09:00", closes: "17:00",
    crowdNote: "The most visited building in Kyoto. A one-way path past the pavilion, and by eleven it is a queue for the one photograph.",
    tip: "Go at opening. Forty-five minutes is plenty — the pavilion is the visit. The tea house near the exit is a fine place to let the crowd pass.",
    cost: 500, pairs: ["kyt-ryoanji"], sources: ["shokoku-ji.jp"] }),

  draft({ id: "kyt-ryoanji", city: c, name: "Ryoan-ji", nameJa: "龍安寺", category: "temple", lat: 35.0345, lon: 135.7183,
    station: "ryoanji-mae", walk: 3, tags: ["shrines", "art"], energy: 0.2, crowd: 0.6, discovery: 0.3, signature: 0.7,
    taste: 20, typical: 45, full: 70, opens: "08:00", closes: "17:00",
    crowdNote: "The rock garden veranda fills with people trying to see all fifteen stones. Early or late it is what it is meant to be.",
    tip: "Fifteen stones, and from any seat you can see fourteen — that is the design. Ten minutes on foot or one bus stop from Kinkaku-ji; do them together.",
    cost: 600, pairs: ["kyt-kinkakuji", "kyt-ninnaji"], sources: ["ryoanji.jp"] }),

  draft({ id: "kyt-ninnaji", city: c, name: "Ninna-ji", nameJa: "仁和寺", category: "temple", lat: 35.0310, lon: 135.7140,
    station: "ryoanji-mae", walk: 12, tags: ["shrines", "history"], energy: 0.3, crowd: 0.3, discovery: 0.55, signature: 0.5,
    taste: 30, typical: 60, full: 90, opens: "09:00", closes: "17:00",
    crowdNote: "Wide grounds, few people — except for its late-blooming cherries in mid-April, which draw the city.",
    tip: "Third in the Kinkaku-ji, Ryoan-ji line and the one most people drop. Keep it if you want a temple with room to breathe; drop it if the day is tight.",
    cost: 800, seasons: ["sakura"], pairs: ["kyt-ryoanji"], sources: ["ninnaji.jp"] }),

  draft({ id: "kyt-arashiyama-bamboo", city: c, name: "Arashiyama Bamboo Grove", nameJa: "嵐山 竹林の小径", category: "nature", lat: 35.0170, lon: 135.6717,
    station: "saga-arashiyama", walk: 12, tags: ["nature"], energy: 0.35, crowd: 0.9, discovery: 0.1, signature: 0.8,
    taste: 20, typical: 45, full: 90, window: ["before 08:00"],
    crowdNote: "A 300-metre path. After nine it is a slow procession with rickshaws pushing through; at seven it is silent and green.",
    tip: "It is shorter than you think. Come at dawn, then Tenryu-ji opens at 8:30 next door. The whole of Arashiyama is a half-day, and it is on the opposite side of the city from Fushimi Inari.",
    cost: 0, conflicts: ["kyt-fushimi-inari"], pairs: ["kyt-tenryuji", "kyt-togetsukyo"], seasons: ["koyo"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-tenryuji", city: c, name: "Tenryu-ji", nameJa: "天龍寺", category: "temple", lat: 35.0157, lon: 135.6738,
    station: "saga-arashiyama", walk: 12, tags: ["shrines", "nature"], energy: 0.25, crowd: 0.7, discovery: 0.2, signature: 0.7,
    taste: 30, typical: 60, full: 90, opens: "08:30", closes: "17:00",
    crowdNote: "Busy by mid-morning because it shares an exit with the bamboo grove. The garden is big enough to absorb it.",
    tip: "The garden is from 1339 and is the thing; you can skip the buildings. Its north gate opens straight into the bamboo grove.",
    cost: 500, seasons: ["koyo"], pairs: ["kyt-arashiyama-bamboo"], sources: ["tenryuji.com"] }),

  draft({ id: "kyt-togetsukyo", city: c, name: "Togetsukyo Bridge", nameJa: "渡月橋", category: "viewpoint", lat: 35.0125, lon: 135.6775,
    station: "saga-arashiyama", walk: 18, tags: ["nature"], energy: 0.15, crowd: 0.7, discovery: 0.1, signature: 0.6,
    taste: 10, typical: 25, full: 45,
    crowdNote: "The bridge and its approach are the busiest part of Arashiyama all day.",
    tip: "The view of the hills from the bridge is the postcard; the river bank on the far side is where to sit with it. In autumn the hillside behind is the point.",
    cost: 0, seasons: ["koyo"], pairs: ["kyt-arashiyama-bamboo", "kyt-monkey-park"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-okochi-sanso", city: c, name: "Okochi Sanso Villa", nameJa: "大河内山荘", category: "garden", lat: 35.0180, lon: 135.6690,
    station: "saga-arashiyama", walk: 18, tags: ["nature", "history"], energy: 0.4, crowd: 0.2, discovery: 0.75, signature: 0.5, physical: 0.4,
    taste: 30, typical: 60, full: 75, opens: "09:00", closes: "17:00",
    crowdNote: "Almost empty, because it costs and it is at the top of the bamboo path where most people turn round.",
    tip: "A film star's hillside garden with the best view over Kyoto in Arashiyama. The ticket includes tea and a sweet — sit down for it.",
    cost: 1000, skipIf: ["limited_mobility"], seasons: ["koyo"], pairs: ["kyt-arashiyama-bamboo"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-monkey-park", city: c, name: "Iwatayama Monkey Park", nameJa: "嵐山モンキーパーク", category: "nature", lat: 35.0095, lon: 135.6770,
    station: "saga-arashiyama", walk: 25, tags: ["nature"], energy: 0.7, crowd: 0.5, discovery: 0.3, signature: 0.5, physical: 0.7,
    taste: 45, typical: 75, full: 100, opens: "09:00", closes: "16:30",
    crowdNote: "A steady stream of families. Never a queue, but the summit hut can be full of people feeding monkeys.",
    tip: "A twenty-minute uphill walk to reach the monkeys — genuinely steep. The view over the city from the top is the reward for people who came for the monkeys and got bored.",
    cost: 800, skipIf: ["limited_mobility"], pairs: ["kyt-togetsukyo"], sources: ["monkeypark.jp"] }),

  draft({ id: "kyt-sagano-train", city: c, name: "Sagano Romantic Train", nameJa: "嵯峨野トロッコ列車", category: "nature", lat: 35.0180, lon: 135.6790,
    station: "saga-arashiyama", walk: 5, tags: ["nature"], energy: 0.1, crowd: 0.7, discovery: 0.3, signature: 0.5,
    taste: 30, typical: 60, full: 120, booking: "recommended", lead: 30, closedWeekdays: [3],
    crowdNote: "Sells out weeks ahead in November. Off-season you can walk up and buy a ticket.",
    tip: "Twenty-five minutes along the gorge in an open carriage. Sit on the right heading out. Closed Wednesdays and all winter — check before you plan around it.",
    cost: 880, seasons: ["koyo", "sakura"], sources: ["sagano-kanko.co.jp"] }),

  draft({ id: "kyt-kennin-ji", city: c, name: "Kennin-ji", nameJa: "建仁寺", category: "temple", lat: 35.0004, lon: 135.7736,
    station: "gion-shijo", walk: 6, tags: ["shrines", "art"], energy: 0.2, crowd: 0.3, discovery: 0.6, signature: 0.5,
    taste: 25, typical: 45, full: 60, opens: "10:00", closes: "17:00",
    crowdNote: "Behind Gion and remarkably quiet given where it is.",
    tip: "The twin dragons painted across the ceiling of the Dharma hall are the reason to come. Kyoto's oldest Zen temple, and you can sit on the veranda as long as you like.",
    cost: 800, pairs: ["kyt-gion"], sources: ["kenninji.jp"] }),

  draft({ id: "kyt-fushimi-sake", city: c, name: "Fushimi sake district", nameJa: "伏見 酒蔵", category: "district", lat: 34.9330, lon: 135.7620,
    station: null, walk: null, tags: ["food", "history"], energy: 0.25, crowd: 0.3, discovery: 0.65, signature: 0.5,
    taste: 45, typical: 90, full: 150, opens: "09:30", closes: "16:30",
    crowdNote: "Quiet canals, white-walled breweries, and a tasting room that fills only on weekend afternoons.",
    tip: "The Gekkeikan Okura museum ticket comes with a tasting. Twenty minutes south of Fushimi Inari by Keihan — a natural afternoon after the shrine at dawn.",
    cost: 600, pairs: ["kyt-fushimi-inari"], sources: ["gekkeikan.co.jp"] }),

  draft({ id: "kyt-kurama-kibune", city: c, name: "Kurama to Kibune trail", nameJa: "鞍馬・貴船", category: "hike", lat: 35.1170, lon: 135.7710,
    station: null, walk: null, tags: ["nature", "shrines"], energy: 0.8, crowd: 0.4, discovery: 0.6, signature: 0.6, physical: 0.8,
    taste: 120, typical: 180, full: 300, opens: "09:00", closes: "16:30",
    crowdNote: "Busy on autumn weekends; quiet on weekdays.",
    tip: "A proper mountain walk between two temples, about two hours with the climb. Kibune's riverside restaurants are the reward. Half a day including the train from Demachiyanagi.",
    cost: 500, skipIf: ["limited_mobility"], seasons: ["koyo"], sources: ["wikivoyage"] }),

  draft({ id: "kyt-railway-museum", city: c, name: "Kyoto Railway Museum", nameJa: "京都鉄道博物館", category: "museum", lat: 34.9870, lon: 135.7420,
    station: "kyoto", walk: 20, tags: ["popculture", "history"], energy: 0.2, crowd: 0.5, discovery: 0.4, signature: 0.4,
    taste: 60, typical: 120, full: 180, opens: "10:00", closes: "17:00", closedWeekdays: [3],
    crowdNote: "Families at weekends and in school holidays; calm on weekdays.",
    tip: "Closed Wednesdays. Fifty-odd real locomotives, a working turntable, and a rooftop deck where the actual Shinkansen passes below. The best rainy-day option with children in Kyoto.",
    cost: 1500, sources: ["kyotorailwaymuseum.jp"] }),

  draft({ id: "kyt-kyoto-tower", city: c, name: "Kyoto Tower", nameJa: "京都タワー", category: "viewpoint", lat: 34.9875, lon: 135.7593,
    station: "kyoto", walk: 3, tags: ["popculture"], energy: 0.1, crowd: 0.5, discovery: 0.05, signature: 0.3,
    taste: 20, typical: 30, full: 45, opens: "10:00", closes: "21:00",
    crowdNote: "Never a long wait; never especially memorable.",
    tip: "Famous but thin: a view of a low city from a modest height. If you want the view of Kyoto, walk up Kiyomizu-dera. If you are killing an hour by the station in the rain, fine.",
    cost: 900, sources: ["kyoto-tower.jp"] }),
];
