import { draft, type PlaceSeed } from "./types";

const c = "nara-city";

/** Nara — 17 drafts. Seed values throughout; verify hours and prices. */
export const nara: PlaceSeed[] = [
  draft({ id: "nra-todaiji", city: c, name: "Todai-ji", nameJa: "東大寺", category: "temple", lat: 34.6890, lon: 135.8398,
    station: "kintetsu-nara", walk: 20, tags: ["shrines", "history"], energy: 0.3, crowd: 0.9, discovery: 0.05, signature: 0.95,
    taste: 30, typical: 60, full: 100, window: ["before 09:00"], opens: "07:30", closes: "17:30",
    crowdNote: "School groups from mid-morning; the hall is big enough that it never quite feels full, but the approach does.",
    tip: "The largest bronze Buddha in Japan in one of the largest wooden buildings in the world. Come at 7:30 when it opens and you get the hall almost alone. The pillar with a hole in it is for children.",
    cost: 800, pairs: ["nra-nara-park", "nra-nigatsudo"], sources: ["todaiji.or.jp"] }),

  draft({ id: "nra-nara-park", city: c, name: "Nara Park & the deer", nameJa: "奈良公園", category: "park", lat: 34.6851, lon: 135.8430,
    station: "kintetsu-nara", walk: 5, tags: ["nature"], energy: 0.3, crowd: 0.7, discovery: 0.05, signature: 0.8,
    taste: 30, typical: 60, full: 120,
    crowdNote: "The deer are everywhere and so are the people feeding them. It thins out the further you walk from the station.",
    tip: "Buy the crackers, hold them up, and the deer bow — then they push. Keep paper and maps out of reach; they eat those too. The park connects everything: Todai-ji, Kasuga, Kofuku-ji are all inside it.",
    cost: 0, pairs: ["nra-todaiji", "nra-kasuga-taisha", "nra-kofukuji"], seasons: ["koyo", "sakura"], sources: ["wikivoyage"] }),

  draft({ id: "nra-kasuga-taisha", city: c, name: "Kasuga Taisha", nameJa: "春日大社", category: "shrine", lat: 34.6815, lon: 135.8483,
    station: "kintetsu-nara", walk: 25, tags: ["shrines", "nature"], energy: 0.35, crowd: 0.5, discovery: 0.3, signature: 0.8,
    taste: 30, typical: 60, full: 90, opens: "06:30", closes: "17:30",
    crowdNote: "The approach through the forest thins the crowd; the inner shrine is busy but moves.",
    tip: "Three thousand lanterns — stone ones lining the forest path, bronze ones hanging in the shrine. The dark room where they are all lit is the thing to pay for. The walk in from the park is part of it.",
    cost: 500, pairs: ["nra-nara-park"], sources: ["kasugataisha.or.jp"] }),

  draft({ id: "nra-kofukuji", city: c, name: "Kofuku-ji", nameJa: "興福寺", category: "temple", lat: 34.6830, lon: 135.8320,
    station: "kintetsu-nara", walk: 5, tags: ["shrines", "history", "art"], energy: 0.2, crowd: 0.5, discovery: 0.3, signature: 0.7,
    taste: 20, typical: 45, full: 75, opens: "09:00", closes: "17:00",
    crowdNote: "Grounds are open and roomy. The treasure hall has a short queue on weekends.",
    tip: "The five-storey pagoda is the symbol of Nara and free to walk around. Pay for the National Treasure Hall: the Ashura statue inside is the most famous sculpture in Japan for a reason.",
    cost: 700, pairs: ["nra-nara-park", "nra-sarusawa-pond"], sources: ["kohfukuji.com"] }),

  draft({ id: "nra-isuien", city: c, name: "Isuien Garden", nameJa: "依水園", category: "garden", lat: 34.6880, lon: 135.8375,
    station: "kintetsu-nara", walk: 15, tags: ["nature"], energy: 0.15, crowd: 0.2, discovery: 0.7, signature: 0.5,
    taste: 30, typical: 45, full: 70, opens: "09:30", closes: "16:30", closedWeekdays: [2],
    crowdNote: "Nearly empty. A dozen people on a busy day.",
    tip: "Closed Tuesdays. Two gardens, one older than the other, with Todai-ji's gate borrowed as scenery. Two minutes from Todai-ji and a fraction of the visitors. Tea in the pavilion is worth the wait.",
    cost: 1200, seasons: ["koyo"], pairs: ["nra-todaiji", "nra-yoshikien"], sources: ["isuien.or.jp"] }),

  draft({ id: "nra-yoshikien", city: c, name: "Yoshikien Garden", nameJa: "吉城園", category: "garden", lat: 34.6875, lon: 135.8365,
    station: "kintetsu-nara", walk: 15, tags: ["nature"], energy: 0.15, crowd: 0.15, discovery: 0.75, signature: 0.4,
    taste: 20, typical: 30, full: 45, opens: "09:00", closes: "17:00",
    crowdNote: "Empty. Genuinely.",
    tip: "Next door to Isuien, smaller, and free — the moss garden and the thatched tea house are the whole thing. Twenty minutes of quiet between two crowded temples.",
    cost: 0, seasons: ["koyo"], pairs: ["nra-isuien"], sources: ["wikivoyage"] }),

  draft({ id: "nra-naramachi", city: c, name: "Naramachi", nameJa: "ならまち", category: "district", lat: 34.6780, lon: 135.8300,
    station: "kintetsu-nara", walk: 12, tags: ["history", "shopping", "food"], energy: 0.25, crowd: 0.3, discovery: 0.5, signature: 0.5,
    taste: 30, typical: 60, full: 120,
    crowdNote: "Calm — most day-trippers never leave the park.",
    tip: "The old merchant quarter south of the park: lattice-fronted houses, small cafés, a free machiya you can walk through. The red cloth monkeys hanging outside doors are charms. A good late afternoon.",
    cost: 0, pairs: ["nra-sarusawa-pond"], sources: ["wikivoyage"] }),

  draft({ id: "nra-nigatsudo", city: c, name: "Nigatsu-do", nameJa: "二月堂", category: "viewpoint", lat: 34.6905, lon: 135.8445,
    station: "kintetsu-nara", walk: 30, tags: ["shrines", "nature"], energy: 0.4, crowd: 0.3, discovery: 0.55, signature: 0.6, physical: 0.4,
    taste: 15, typical: 30, full: 45,
    crowdNote: "A few people on the balcony at any time; empty at dusk, which is when to be there.",
    tip: "A hall on stilts up the hill behind Todai-ji, free and open all hours, with the best view over Nara. Sunset from the balcony is the best free thing in the city.",
    cost: 0, skipIf: ["limited_mobility"], pairs: ["nra-todaiji"], sources: ["todaiji.or.jp"] }),

  draft({ id: "nra-national-museum", city: c, name: "Nara National Museum", nameJa: "奈良国立博物館", category: "museum", lat: 34.6840, lon: 135.8380,
    station: "kintetsu-nara", walk: 12, tags: ["art", "history"], energy: 0.15, crowd: 0.3, discovery: 0.4, signature: 0.5,
    taste: 45, typical: 90, full: 150, opens: "09:30", closes: "17:00", closedWeekdays: [1],
    crowdNote: "Calm, except during the Shosoin exhibition each autumn, when the queue crosses the park.",
    tip: "Closed Mondays. The Buddhist sculpture hall is the finest single room of its kind in Japan — go for that alone. In the park, so it fits between Kofuku-ji and Todai-ji.",
    cost: 700, sources: ["narahaku.go.jp"] }),

  draft({ id: "nra-horyuji", city: c, name: "Horyu-ji", nameJa: "法隆寺", category: "temple", lat: 34.6146, lon: 135.7342,
    station: "horyuji", walk: 20, tags: ["shrines", "history"], energy: 0.35, crowd: 0.3, discovery: 0.5, signature: 0.8,
    taste: 45, typical: 90, full: 150, opens: "08:00", closes: "17:00",
    crowdNote: "Never crowded — it is outside the city and most day-trippers do not get here.",
    tip: "The oldest wooden buildings in the world, from about 600 AD, and quiet. Twelve minutes by train from Nara then a walk or bus. A half-day; do it on the way to or from Osaka.",
    cost: 1500, sources: ["horyuji.or.jp"] }),

  draft({ id: "nra-toshodaiji", city: c, name: "Toshodai-ji", nameJa: "唐招提寺", category: "temple", lat: 34.6756, lon: 135.7847,
    station: null, walk: null, tags: ["shrines", "history"], energy: 0.3, crowd: 0.2, discovery: 0.65, signature: 0.6,
    taste: 30, typical: 60, full: 90, opens: "08:30", closes: "17:00",
    crowdNote: "Quiet. Nishinokyo gets a fraction of the park's visitors.",
    tip: "Founded by the blind Chinese monk Ganjin in 759, and the main hall is the great Nara-period building still standing. Five minutes' walk from Yakushi-ji; do both from Nishinokyo station on the Kintetsu line.",
    cost: 1000, pairs: ["nra-yakushiji"], sources: ["toshodaiji.jp"] }),

  draft({ id: "nra-yakushiji", city: c, name: "Yakushi-ji", nameJa: "薬師寺", category: "temple", lat: 34.6685, lon: 135.7845,
    station: null, walk: null, tags: ["shrines", "history"], energy: 0.3, crowd: 0.2, discovery: 0.6, signature: 0.6,
    taste: 30, typical: 60, full: 90, opens: "08:30", closes: "17:00",
    crowdNote: "Quiet.",
    tip: "Twin pagodas, one from 730 and one rebuilt in 1981 — stand between them and see the difference twelve centuries makes. Pair with Toshodai-ji next door.",
    cost: 1000, pairs: ["nra-toshodaiji"], sources: ["yakushiji.or.jp"] }),

  draft({ id: "nra-heijo-palace", city: c, name: "Heijo Palace site", nameJa: "平城宮跡", category: "park", lat: 34.6910, lon: 135.7950,
    station: null, walk: null, tags: ["history", "nature"], energy: 0.4, crowd: 0.15, discovery: 0.7, signature: 0.4, physical: 0.4,
    taste: 30, typical: 60, full: 120, opens: "09:00", closes: "16:30", closedWeekdays: [1],
    crowdNote: "Empty fields with a few reconstructed gates; you may see nobody.",
    tip: "Where the capital was, 710–784, before Kyoto. Mostly grass, with the great gate and a hall rebuilt at full size. For people who like the idea of a place more than the place. Bring a bicycle.",
    cost: 0, sources: ["heijo-park.jp"] }),

  draft({ id: "nra-wakakusa", city: c, name: "Mount Wakakusa", nameJa: "若草山", category: "viewpoint", lat: 34.6870, lon: 135.8560,
    station: "kintetsu-nara", walk: 35, tags: ["nature"], energy: 0.55, crowd: 0.3, discovery: 0.5, signature: 0.5, physical: 0.6,
    taste: 30, typical: 60, full: 90, opens: "09:00", closes: "17:00",
    crowdNote: "A few walkers and a lot of deer.",
    tip: "A grass hill behind the park; twenty minutes of steps to the first summit and a view over the whole plain. Closed in winter, and burned deliberately each January in a festival. Deer follow you up.",
    cost: 150, skipIf: ["limited_mobility"], pairs: ["nra-nara-park"], sources: ["wikivoyage"] }),

  draft({ id: "nra-kasugayama-forest", city: c, name: "Kasugayama Primeval Forest", nameJa: "春日山原始林", category: "hike", lat: 34.6830, lon: 135.8620,
    station: null, walk: null, tags: ["nature"], energy: 0.8, crowd: 0.1, discovery: 0.8, signature: 0.4, physical: 0.8,
    taste: 90, typical: 150, full: 240,
    crowdNote: "You will meet more deer than people.",
    tip: "A forest untouched since 841, when hunting and logging were banned. A 10 km loop on forest roads behind Kasuga Taisha. A real half-day walk; not for a tight schedule.",
    cost: 0, skipIf: ["limited_mobility"], seasons: ["koyo"], sources: ["wikivoyage"] }),

  draft({ id: "nra-nakatanidou", city: c, name: "Nakatanidou mochi", nameJa: "中谷堂", category: "food", lat: 34.6815, lon: 135.8290,
    station: "kintetsu-nara", walk: 3, tags: ["food"], energy: 0.05, crowd: 0.6, discovery: 0.3, signature: 0.5,
    taste: 10, typical: 15, full: 25, opens: "10:00", closes: "19:00",
    crowdNote: "A crowd gathers whenever the pounding starts, which is every half hour or so.",
    tip: "The fastest mochi-pounders in Japan, hammering rice at a rate that looks dangerous. Watch, then buy one warm for a few hundred yen. Ten minutes and worth every one.",
    cost: 200, sources: ["nakatanidou.jp"] }),

  draft({ id: "nra-sarusawa-pond", city: c, name: "Sarusawa Pond", nameJa: "猿沢池", category: "viewpoint", lat: 34.6810, lon: 135.8310,
    station: "kintetsu-nara", walk: 5, tags: ["nature"], energy: 0.05, crowd: 0.3, discovery: 0.4, signature: 0.3,
    taste: 10, typical: 15, full: 30,
    crowdNote: "Never busy.",
    tip: "The pagoda of Kofuku-ji reflected in a pond with willows and turtles — the classic Nara view, free, five minutes from the station. Best at dusk.",
    cost: 0, pairs: ["nra-kofukuji", "nra-naramachi"], sources: ["wikivoyage"] }),

  draft({ id: "nra-gangoji", city: c, name: "Gango-ji", nameJa: "元興寺", category: "temple", lat: 34.6775, lon: 135.8305,
    station: "kintetsu-nara", walk: 12, tags: ["shrines", "history"], energy: 0.15, crowd: 0.2, discovery: 0.65, signature: 0.5,
    taste: 20, typical: 40, full: 60, opens: "09:00", closes: "17:00",
    crowdNote: "Quiet — it sits inside Naramachi and most people walk past the gate.",
    tip: "World Heritage and almost unvisited. Some of the roof tiles are from the 6th century, moved here from Japan's first temple at Asuka; look for the darker, rougher ones. Twenty minutes is enough.",
    cost: 500, pairs: ["nra-naramachi"], sources: ["gangoji-tera.or.jp"] }),

  draft({ id: "nra-shin-yakushiji", city: c, name: "Shin-Yakushi-ji", nameJa: "新薬師寺", category: "temple", lat: 34.6765, lon: 135.8455,
    station: null, walk: null, tags: ["shrines", "art"], energy: 0.2, crowd: 0.1, discovery: 0.85, signature: 0.5,
    taste: 20, typical: 40, full: 60, opens: "09:00", closes: "17:00",
    crowdNote: "A handful of people in the hall at any time.",
    tip: "One hall, one 8th-century Buddha, and the Twelve Heavenly Generals ringed around it in clay — the finest set in Japan and you stand a metre from them. Twenty minutes' walk south-east of the park through the Takabatake lanes.",
    cost: 600, sources: ["shinyakushiji.or.jp"] }),

  draft({ id: "nra-todaiji-museum", city: c, name: "Todai-ji Museum", nameJa: "東大寺ミュージアム", category: "museum", lat: 34.6875, lon: 135.8385,
    station: "kintetsu-nara", walk: 18, tags: ["art", "history"], energy: 0.1, crowd: 0.3, discovery: 0.5, signature: 0.4,
    taste: 30, typical: 45, full: 75, opens: "09:30", closes: "17:30",
    crowdNote: "Calm even when the Great Buddha Hall outside is heaving.",
    tip: "The statues that used to live in the temple's older halls, lit properly for once — the Nikko and Gakko bodhisattvas are the reason. The combined ticket with the Great Buddha Hall saves a few hundred yen.",
    cost: 600, pairs: ["nra-todaiji"], sources: ["todaiji.or.jp"] }),

  draft({ id: "nra-ukimido", city: c, name: "Ukimido Pavilion", nameJa: "浮見堂", category: "viewpoint", lat: 34.6805, lon: 135.8405,
    station: "kintetsu-nara", walk: 12, tags: ["nature"], energy: 0.05, crowd: 0.2, discovery: 0.6, signature: 0.3,
    taste: 10, typical: 20, full: 30,
    crowdNote: "A few people on the bridge; deer at the water's edge.",
    tip: "A hexagonal pavilion on a pond in the southern half of the park, lit at night and ringed with cherry trees in April. Ten minutes, on the way between Kasuga Taisha and Naramachi.",
    cost: 0, pairs: ["nra-nara-park"], seasons: ["sakura"], sources: ["wikivoyage"] }),

  draft({ id: "nra-saidaiji", city: c, name: "Saidai-ji", nameJa: "西大寺", category: "temple", lat: 34.6935, lon: 135.7815,
    station: null, walk: null, tags: ["shrines", "history"], energy: 0.15, crowd: 0.15, discovery: 0.75, signature: 0.4,
    taste: 20, typical: 40, full: 60, opens: "08:30", closes: "16:30",
    crowdNote: "Empty outside its tea festivals.",
    tip: "The 'Great Western Temple' that once balanced Todai-ji in the east, now a quiet compound three minutes from Yamato-Saidaiji station — the Kintetsu junction you change at anyway. Known for the Ochamori ceremony, where tea is drunk from a bowl the size of a basin.",
    cost: 800, sources: ["saidaiji.or.jp"] }),

  draft({ id: "nra-hokkeji", city: c, name: "Hokke-ji", nameJa: "法華寺", category: "temple", lat: 34.6935, lon: 135.8005,
    station: null, walk: null, tags: ["shrines", "history"], energy: 0.15, crowd: 0.1, discovery: 0.85, signature: 0.4,
    taste: 20, typical: 30, full: 50, opens: "09:00", closes: "17:00",
    crowdNote: "You may be the only visitor.",
    tip: "A convent founded by Empress Komyo in 745 on the site of her father's mansion, with a small garden and a famous Eleven-headed Kannon shown only a few weeks a year. Ten minutes by bus from either Nara station, next to the Heijo Palace site.",
    cost: 700, pairs: ["nra-heijo-palace"], sources: ["hokkeji-nara.jp"] }),

  draft({ id: "nra-harushika", city: c, name: "Harushika sake brewery", nameJa: "春鹿醸造元", category: "food", lat: 34.6785, lon: 135.8320,
    station: "kintetsu-nara", walk: 12, tags: ["food"], energy: 0.05, crowd: 0.3, discovery: 0.6, signature: 0.4,
    taste: 20, typical: 30, full: 45, opens: "10:00", closes: "17:00",
    crowdNote: "A short wait for a tasting slot on weekend afternoons.",
    tip: "Five hundred yen buys a tasting of five sakes and you keep the glass. In Naramachi, and the brewery has been here since 1884 — Nara is where sake as we know it was first brewed.",
    cost: 500, pairs: ["nra-naramachi"], sources: ["harushika.com"] }),

  draft({ id: "nra-higashimuki", city: c, name: "Higashimuki arcade", nameJa: "東向商店街", category: "shopping", lat: 34.6825, lon: 135.8285,
    station: "kintetsu-nara", walk: 1, tags: ["shopping", "food"], energy: 0.15, crowd: 0.6, discovery: 0.1, signature: 0.3,
    taste: 15, typical: 30, full: 60,
    crowdNote: "Busy in the middle of the day; it is the main way from the station to the park.",
    tip: "A covered street from the Kintetsu station exit down to Sanjo-dori — lunch, kakinoha-zushi (mackerel pressed in persimmon leaves), deer souvenirs. Not a destination; the practical answer to 'where do we eat'.",
    cost: 0, pairs: ["nra-nakatanidou"], sources: ["wikivoyage"] }),

  draft({ id: "nra-byakugoji", city: c, name: "Byakugo-ji", nameJa: "白毫寺", category: "temple", lat: 34.6715, lon: 135.8475,
    station: null, walk: null, tags: ["shrines", "nature"], energy: 0.35, crowd: 0.1, discovery: 0.9, signature: 0.4, physical: 0.4,
    taste: 20, typical: 40, full: 60, opens: "09:00", closes: "17:00",
    crowdNote: "Empty, except for a week or two when the camellias are out.",
    tip: "Stone steps up between hedges to a terrace with a view over the whole Nara basin — the reason to come. Twenty-five minutes' walk south-east of the park; pair it with Shin-Yakushi-ji, ten minutes away.",
    cost: 500, skipIf: ["limited_mobility"], pairs: ["nra-shin-yakushiji"], seasons: ["sakura"], sources: ["wikivoyage"] }),
];
