import { draft, type PlaceSeed } from "./types";

const c = "osaka-city";

/** Osaka — 28 drafts. Seed values throughout; verify hours and prices. */
export const osaka: PlaceSeed[] = [
  draft({ id: "osk-osaka-castle", city: c, name: "Osaka Castle", nameJa: "大阪城", category: "castle", lat: 34.6873, lon: 135.5262,
    station: "osakajokoen", walk: 15, tags: ["history"], energy: 0.35, crowd: 0.75, discovery: 0.1, signature: 0.8, physical: 0.4,
    taste: 45, typical: 90, full: 150, window: ["before 09:30"], opens: "09:00", closes: "17:00",
    crowdNote: "The keep is a museum with a lift queue. Weekend afternoons the wait for the lift is longer than the visit.",
    tip: "The keep is a 1931 concrete reconstruction with a museum inside; the view from the top and the walls and moats outside are the real castle. Walk the outer wall before going in.",
    cost: 600, pairs: ["osk-castle-park"], seasons: ["sakura"], sources: ["osakacastle.net"] }),

  draft({ id: "osk-castle-park", city: c, name: "Osaka Castle Park", nameJa: "大阪城公園", category: "park", lat: 34.6900, lon: 135.5300,
    station: "osakajokoen", walk: 5, tags: ["nature"], energy: 0.3, crowd: 0.4, discovery: 0.2, signature: 0.4,
    taste: 20, typical: 45, full: 90,
    crowdNote: "Roomy, except in the first week of April when the plum and cherry groves draw the city.",
    tip: "The Nishinomaru garden costs a little and has the classic view of the keep across the moat. Runners and dog walkers at dawn; a good jet-lag morning.",
    cost: 0, seasons: ["sakura"], pairs: ["osk-osaka-castle"], sources: ["osakacastlepark.jp"] }),

  draft({ id: "osk-dotonbori", city: c, name: "Dotonbori", nameJa: "道頓堀", category: "district", lat: 34.6687, lon: 135.5013,
    station: "namba", walk: 5, tags: ["food", "nightlife", "popculture"], energy: 0.2, crowd: 0.95, discovery: 0.05, signature: 0.9,
    taste: 30, typical: 75, full: 150, window: ["after 17:30"],
    crowdNote: "Packed every evening of the year. That is the point; go when it is loud.",
    tip: "The Glico running man is on the bridge; everyone photographs it and moves on. The food is why you are here — takoyaki, kushikatsu, okonomiyaki — and the side streets are better than the canal front.",
    cost: 0, pairs: ["osk-hozenji", "osk-kuromon"], sources: ["wikivoyage"] }),

  draft({ id: "osk-hozenji", city: c, name: "Hozenji Yokocho", nameJa: "法善寺横丁", category: "street", lat: 34.6675, lon: 135.5030,
    station: "namba", walk: 6, tags: ["food", "history"], energy: 0.1, crowd: 0.5, discovery: 0.55, signature: 0.5,
    taste: 10, typical: 30, full: 60, window: ["after 17:30"],
    crowdNote: "Two lantern-lit lanes a minute from Dotonbori and a different century. Never crowded — most people walk past the entrance.",
    tip: "Throw water on the moss-covered Fudo statue at the tiny temple; that is the ritual. Then eat at any of the counters — it is the calm alternative to the canal.",
    cost: 0, pairs: ["osk-dotonbori"], sources: ["wikivoyage"] }),

  draft({ id: "osk-kuromon", city: c, name: "Kuromon Market", nameJa: "黒門市場", category: "market", lat: 34.6640, lon: 135.5060,
    station: "nippombashi", walk: 3, tags: ["food"], energy: 0.2, crowd: 0.8, discovery: 0.2, signature: 0.6,
    taste: 30, typical: 60, full: 90, window: ["before 11:00"], opens: "09:00", closes: "17:00",
    crowdNote: "Tourist-heavy by late morning and priced accordingly. Early it is still a market.",
    tip: "Grilled seafood eaten standing up. Prices have climbed with the crowds; it is worth it once, for the scallops and the atmosphere, not for a cheap lunch.",
    cost: 0, pairs: ["osk-dotonbori"], sources: ["kuromon.com"] }),

  draft({ id: "osk-shinsekai", city: c, name: "Shinsekai", nameJa: "新世界", category: "district", lat: 34.6525, lon: 135.5063,
    station: "dobutsuen-mae", walk: 5, tags: ["food", "nightlife", "history"], energy: 0.2, crowd: 0.6, discovery: 0.4, signature: 0.6,
    taste: 30, typical: 60, full: 120, window: ["after 17:30"],
    crowdNote: "Lively in the evening, a little forlorn by day. Weekends are its natural state.",
    tip: "Retro Osaka — kushikatsu (skewers) is the dish, and the rule is no double-dipping in the sauce. Rougher-edged than Dotonbori and better for it.",
    cost: 0, pairs: ["osk-tsutenkaku", "osk-spa-world"], sources: ["wikivoyage"] }),

  draft({ id: "osk-tsutenkaku", city: c, name: "Tsutenkaku Tower", nameJa: "通天閣", category: "viewpoint", lat: 34.6525, lon: 135.5063,
    station: "dobutsuen-mae", walk: 7, tags: ["popculture"], energy: 0.1, crowd: 0.5, discovery: 0.2, signature: 0.4,
    taste: 20, typical: 40, full: 60, opens: "10:00", closes: "20:00",
    crowdNote: "Short waits; the observation deck is small.",
    tip: "Loved for what it is, not for the view. Rub the Billiken statue's feet for luck and come back down — the neighbourhood around it is the attraction.",
    cost: 900, pairs: ["osk-shinsekai"], sources: ["tsutenkaku.co.jp"] }),

  draft({ id: "osk-spa-world", city: c, name: "Spa World", nameJa: "スパワールド", category: "onsen", lat: 34.6510, lon: 135.5050,
    station: "dobutsuen-mae", walk: 5, tags: ["onsen"], energy: 0.1, crowd: 0.5, discovery: 0.3, signature: 0.4,
    taste: 60, typical: 120, full: 240, opens: "10:00", closes: "23:59",
    crowdNote: "Busy on weekend evenings. Weekday afternoons you can have a themed bath to yourself.",
    tip: "A vast bath complex with 'European' and 'Asian' floors that swap between men and women monthly. Tattoos are not allowed. A good way to spend a rainy afternoon in the south of the city.",
    cost: 1500, pairs: ["osk-shinsekai"], sources: ["spaworld.co.jp"] }),

  draft({ id: "osk-shitennoji", city: c, name: "Shitenno-ji", nameJa: "四天王寺", category: "temple", lat: 34.6537, lon: 135.5164,
    station: "tennoji", walk: 10, tags: ["shrines", "history"], energy: 0.25, crowd: 0.3, discovery: 0.5, signature: 0.5,
    taste: 30, typical: 60, full: 90, opens: "08:30", closes: "16:30",
    crowdNote: "Quiet except on the 21st and 22nd of each month, when the flea market fills the grounds.",
    tip: "Japan's oldest official temple, founded 593 — and rebuilt in concrete after the war, so it is the layout and the ritual that are old. The garden is the calm part.",
    cost: 300, sources: ["shitennoji.or.jp"] }),

  draft({ id: "osk-abeno-harukas", city: c, name: "Abeno Harukas 300", nameJa: "あべのハルカス", category: "viewpoint", lat: 34.6459, lon: 135.5137,
    station: "tennoji", walk: 3, tags: ["popculture"], energy: 0.1, crowd: 0.6, discovery: 0.1, signature: 0.6,
    taste: 30, typical: 45, full: 75, window: ["after 17:30"], opens: "09:00", closes: "22:00",
    crowdNote: "Sunset slots are busiest; late evening is calm and the view is better anyway.",
    tip: "Japan's tallest building until recently, with a 360° deck on floors 58–60. Go after dark. The 16th-floor garden terrace is free and good enough for many people.",
    cost: 2000, sources: ["abenoharukas-300.jp"] }),

  draft({ id: "osk-tennoji-park", city: c, name: "Tennoji Park & Keitakuen", nameJa: "天王寺公園", category: "park", lat: 34.6510, lon: 135.5100,
    station: "tennoji", walk: 5, tags: ["nature"], energy: 0.2, crowd: 0.4, discovery: 0.4, signature: 0.3,
    taste: 15, typical: 40, full: 75, opens: "09:30", closes: "17:00",
    crowdNote: "Families on the lawn; the Keitakuen garden inside is nearly empty.",
    tip: "The lawn is a good place to sit; Keitakuen is a small formal garden that costs almost nothing and has nobody in it. The zoo is fine for children, skippable otherwise.",
    cost: 150, sources: ["wikivoyage"] }),

  draft({ id: "osk-umeda-sky", city: c, name: "Umeda Sky Building", nameJa: "梅田スカイビル", category: "viewpoint", lat: 34.7053, lon: 135.4900,
    station: "osaka", walk: 10, tags: ["popculture"], energy: 0.1, crowd: 0.6, discovery: 0.2, signature: 0.6,
    taste: 30, typical: 45, full: 75, window: ["after 17:30"], opens: "09:30", closes: "22:30",
    crowdNote: "Sunset draws a queue for the escalator; an hour after dark it moves freely.",
    tip: "The open-air ring at the top is what makes it — wind in your hair, the city all round. The escalator between the two towers, in a glass tube, is half the fun.",
    cost: 2000, sources: ["skybldg.co.jp"] }),

  draft({ id: "osk-kaiyukan", city: c, name: "Osaka Aquarium Kaiyukan", nameJa: "海遊館", category: "aquarium", lat: 34.6545, lon: 135.4290,
    station: "osakako", walk: 5, tags: ["nature", "popculture"], energy: 0.2, crowd: 0.8, discovery: 0.1, signature: 0.6,
    taste: 60, typical: 120, full: 180, booking: "recommended", lead: 7, opens: "10:00", closes: "20:00",
    crowdNote: "Very busy at weekends and in holidays. Weekday late afternoons are the calm window.",
    tip: "One of the best aquariums in the world, built as a spiral around a whale shark tank. Buy a timed ticket online to skip the queue. Forty minutes from the centre — it is a half-day with the ferris wheel next door.",
    cost: 2700, pairs: ["osk-tempozan-wheel"], sources: ["kaiyukan.com"] }),

  draft({ id: "osk-tempozan-wheel", city: c, name: "Tempozan Ferris Wheel", nameJa: "天保山大観覧車", category: "viewpoint", lat: 34.6560, lon: 135.4315,
    station: "osakako", walk: 5, tags: ["popculture"], energy: 0.05, crowd: 0.4, discovery: 0.2, signature: 0.3,
    taste: 15, typical: 25, full: 35, opens: "10:00", closes: "22:00",
    crowdNote: "Short waits outside holidays.",
    tip: "Fifteen minutes round. Next to the aquarium — worth it only if you are already there, and best after dark when the port is lit.",
    cost: 900, pairs: ["osk-kaiyukan"], sources: ["wikivoyage"] }),

  draft({ id: "osk-sumiyoshi-taisha", city: c, name: "Sumiyoshi Taisha", nameJa: "住吉大社", category: "shrine", lat: 34.6125, lon: 135.4930,
    station: null, walk: null, tags: ["shrines", "history"], energy: 0.2, crowd: 0.3, discovery: 0.6, signature: 0.6,
    taste: 30, typical: 50, full: 80, opens: "06:00", closes: "17:00",
    crowdNote: "Quiet on ordinary days; enormous at New Year.",
    tip: "A shrine style older than Buddhism's arrival, with the steeply arched red bridge everyone photographs. Twenty minutes south of Namba on the Nankai line, then a two-minute walk from Sumiyoshi-taisha station.",
    cost: 0, sources: ["sumiyoshitaisha.net"] }),

  draft({ id: "osk-museum-of-history", city: c, name: "Osaka Museum of History", nameJa: "大阪歴史博物館", category: "museum", lat: 34.6830, lon: 135.5200,
    station: "tanimachi-4chome", walk: 2, tags: ["history"], energy: 0.15, crowd: 0.3, discovery: 0.5, signature: 0.5,
    taste: 45, typical: 90, full: 120, opens: "09:30", closes: "17:00", closedWeekdays: [2],
    crowdNote: "Quiet. School groups on weekday mornings.",
    tip: "Closed Tuesdays. Start on the top floor — the reconstructed Naniwa palace hall — and work down through the centuries. The window view of Osaka Castle from up there is the best free castle photograph in the city.",
    cost: 600, pairs: ["osk-osaka-castle"], sources: ["osakamushis.jp"] }),

  draft({ id: "osk-nakanoshima-park", city: c, name: "Nakanoshima Park", nameJa: "中之島公園", category: "park", lat: 34.6925, lon: 135.5100,
    station: "osaka", walk: 15, tags: ["nature"], energy: 0.2, crowd: 0.3, discovery: 0.5, signature: 0.4,
    taste: 20, typical: 40, full: 75,
    crowdNote: "Office workers at lunch, otherwise sparse. The rose garden draws people in May and October.",
    tip: "A long thin island between two rivers, with a rose garden at the east end and the red-brick Central Public Hall. The calm centre of a loud city.",
    cost: 0, pairs: ["osk-nakanoshima-museum"], sources: ["wikivoyage"] }),

  draft({ id: "osk-nakanoshima-museum", city: c, name: "Nakanoshima Museum of Art", nameJa: "大阪中之島美術館", category: "museum", lat: 34.6910, lon: 135.4900,
    station: "osaka", walk: 15, tags: ["art"], energy: 0.15, crowd: 0.4, discovery: 0.4, signature: 0.5,
    taste: 45, typical: 90, full: 150, opens: "10:00", closes: "17:00", closedWeekdays: [1],
    crowdNote: "Depends entirely on the exhibition. The permanent collection floors are calm.",
    tip: "Closed Mondays. Opened 2022, a black cube with Modigliani and Dalí in the permanent collection and strong design shows. The National Museum of Art is next door — one ticket each, plan both.",
    cost: 1500, pairs: ["osk-national-museum-art"], sources: ["nakka-art.jp"] }),

  draft({ id: "osk-national-museum-art", city: c, name: "National Museum of Art, Osaka", nameJa: "国立国際美術館", category: "museum", lat: 34.6915, lon: 135.4915,
    station: "osaka", walk: 18, tags: ["art"], energy: 0.15, crowd: 0.3, discovery: 0.5, signature: 0.4,
    taste: 45, typical: 75, full: 120, opens: "10:00", closes: "17:00", closedWeekdays: [1],
    crowdNote: "Quiet unless a headline show is on.",
    tip: "Closed Mondays. Entirely underground, beneath a steel sculpture that looks like bamboo. Contemporary and postwar Japanese art, cheaply.",
    cost: 430, pairs: ["osk-nakanoshima-museum"], sources: ["nmao.go.jp"] }),

  draft({ id: "osk-shinsaibashi-suji", city: c, name: "Shinsaibashi-suji", nameJa: "心斎橋筋商店街", category: "shopping", lat: 34.6740, lon: 135.5015,
    station: "shinsaibashi", walk: 1, tags: ["shopping"], energy: 0.2, crowd: 0.85, discovery: 0.1, signature: 0.4,
    taste: 30, typical: 60, full: 150,
    crowdNote: "A covered street 600 metres long and always full. Weekend afternoons are a slow drift.",
    tip: "Everything from drugstores to department stores under one roof, ending at Dotonbori. Useful rather than special; the drugstores are where visitors actually spend.",
    cost: 0, pairs: ["osk-amerikamura", "osk-dotonbori"], sources: ["wikivoyage"] }),

  draft({ id: "osk-amerikamura", city: c, name: "Amerikamura", nameJa: "アメリカ村", category: "district", lat: 34.6725, lon: 135.4980,
    station: "shinsaibashi", walk: 5, tags: ["shopping", "popculture", "nightlife"], energy: 0.2, crowd: 0.6, discovery: 0.4, signature: 0.4,
    taste: 20, typical: 45, full: 90, window: ["after 17:30"],
    crowdNote: "Teenagers and vintage shoppers by afternoon; bars by night.",
    tip: "Osaka's Harajuku, more or less — vintage clothes, street food, a small triangle park where everyone sits. Better in the evening.",
    cost: 0, pairs: ["osk-shinsaibashi-suji"], sources: ["wikivoyage"] }),

  draft({ id: "osk-den-den-town", city: c, name: "Den Den Town", nameJa: "でんでんタウン", category: "shopping", lat: 34.6615, lon: 135.5060,
    station: "nippombashi", walk: 3, tags: ["popculture", "shopping"], energy: 0.2, crowd: 0.5, discovery: 0.4, signature: 0.4,
    taste: 30, typical: 60, full: 150, opens: "11:00", closes: "20:00",
    crowdNote: "Busy at weekends, easy on weekdays.",
    tip: "Osaka's Akihabara: anime, figures, retro games, electronics. Smaller and cheaper than Tokyo's, and five minutes from Kuromon Market.",
    cost: 0, pairs: ["osk-kuromon"], sources: ["wikivoyage"] }),

  draft({ id: "osk-namba-yasaka", city: c, name: "Namba Yasaka Shrine", nameJa: "難波八阪神社", category: "shrine", lat: 34.6620, lon: 135.4960,
    station: "namba", walk: 8, tags: ["shrines", "popculture"], energy: 0.1, crowd: 0.4, discovery: 0.55, signature: 0.5,
    taste: 10, typical: 20, full: 30, opens: "06:30", closes: "17:00",
    crowdNote: "A steady trickle for the photograph; rarely more.",
    tip: "A twelve-metre lion's head with a stage inside its mouth. Ten minutes; the surprise is the visit. Free.",
    cost: 0, sources: ["wikivoyage"] }),

  draft({ id: "osk-osaka-tenmangu", city: c, name: "Osaka Tenmangu", nameJa: "大阪天満宮", category: "shrine", lat: 34.6960, lon: 135.5120,
    station: null, walk: null, tags: ["shrines"], energy: 0.15, crowd: 0.3, discovery: 0.5, signature: 0.4,
    taste: 15, typical: 30, full: 45, opens: "09:00", closes: "17:00",
    crowdNote: "Quiet outside the Tenjin festival in late July, which is one of Japan's three biggest.",
    tip: "Dedicated to the god of learning, so students come before exams. Next to Tenjimbashisuji — Japan's longest covered shopping street — which is the better reason to come this way.",
    cost: 0, pairs: ["osk-tenjimbashisuji"], sources: ["tenjinsan.com"] }),

  draft({ id: "osk-tenjimbashisuji", city: c, name: "Tenjimbashisuji Shopping Street", nameJa: "天神橋筋商店街", category: "shopping", lat: 34.7050, lon: 135.5120,
    station: null, walk: null, tags: ["shopping", "food"], energy: 0.3, crowd: 0.5, discovery: 0.6, signature: 0.4,
    taste: 30, typical: 60, full: 120,
    crowdNote: "Locals shopping, not tourists browsing. Comfortable all day.",
    tip: "2.6 km under one roof — the longest in Japan — and the most ordinary-Osaka thing you can do. Cheap lunches, old shops, nobody selling you anything.",
    cost: 0, pairs: ["osk-osaka-tenmangu"], sources: ["wikivoyage"] }),

  draft({ id: "osk-minoo-falls", city: c, name: "Minoo Falls", nameJa: "箕面大滝", category: "nature", lat: 34.8530, lon: 135.4720,
    station: null, walk: null, tags: ["nature"], energy: 0.55, crowd: 0.5, discovery: 0.6, signature: 0.5, physical: 0.5,
    taste: 60, typical: 120, full: 180,
    crowdNote: "Packed on November weekends for the maples; calm the rest of the year.",
    tip: "A flat, paved 3 km riverside walk to a 33-metre waterfall — a valley, not a hike. Thirty minutes from Umeda on the Hankyu line. The deep-fried maple leaves sold along the path are a real thing.",
    cost: 0, skipIf: ["limited_mobility"], seasons: ["koyo"], sources: ["wikivoyage"] }),

  draft({ id: "osk-expo-park", city: c, name: "Expo '70 Park & Tower of the Sun", nameJa: "万博記念公園", category: "park", lat: 34.8090, lon: 135.5330,
    station: null, walk: null, tags: ["art", "nature", "popculture"], energy: 0.35, crowd: 0.4, discovery: 0.5, signature: 0.5,
    taste: 45, typical: 120, full: 240, booking: "recommended", lead: 14, opens: "09:30", closes: "17:00", closedWeekdays: [3],
    crowdNote: "Roomy — it is huge. The Tower interior has timed entry and sells out at weekends.",
    tip: "Closed Wednesdays. Taro Okamoto's Tower of the Sun is the strangest great building in Japan and you can now go inside it — book ahead. Forty minutes from Umeda on the monorail.",
    cost: 260, sources: ["expo70-park.jp"] }),

  draft({ id: "osk-teamlab-botanical", city: c, name: "teamLab Botanical Garden", nameJa: "チームラボ ボタニカルガーデン", category: "garden", lat: 34.6100, lon: 135.5190,
    station: null, walk: null, tags: ["art", "nature", "popculture"], energy: 0.3, crowd: 0.7, discovery: 0.3, signature: 0.6,
    taste: 60, typical: 90, full: 120, booking: "required", lead: 14, window: ["after 17:30"], opens: "18:00", closes: "21:30",
    crowdNote: "Timed entry keeps it moving, but weekend slots sell out a week or two ahead.",
    tip: "Light art across a real botanical garden in Nagai Park, after dark. Book a slot online; it is not a walk-up. Thirty minutes south of Namba on the Midosuji line.",
    cost: 1800, sources: ["teamlab.art"] }),
];
