/**
 * Turns the drafted place seeds into SQL.
 *
 *   npx tsx scripts/export-places-seed.ts > supabase/seed_places_draft.sql
 *
 * Every row lands as a draft. Re-running refreshes DRAFT rows only: a
 * record a human has verified is never overwritten by a re-export — the
 * signature stands until someone withdraws it in /admin.
 */
import { kyoto } from "../src/lib/places/seed/kyoto";
import { osaka } from "../src/lib/places/seed/osaka";
import { nara } from "../src/lib/places/seed/nara";
import { hiroshima } from "../src/lib/places/seed/hiroshima";
import { miyajima } from "../src/lib/places/seed/miyajima";
import { himeji } from "../src/lib/places/seed/himeji";
import type { PlaceSeed } from "../src/lib/places/seed/types";

const all: PlaceSeed[] = [...kyoto, ...osaka, ...nara, ...hiroshima, ...miyajima, ...himeji];

const seen = new Set<string>();
for (const p of all) {
  if (seen.has(p.id)) throw new Error(`duplicate place id ${p.id}`);
  seen.add(p.id);
  for (const c of p.conflicts ?? []) if (!all.some((q) => q.id === c)) throw new Error(`${p.id} conflicts_with unknown ${c}`);
  for (const c of p.pairs ?? []) if (!all.some((q) => q.id === c)) throw new Error(`${p.id} pairs_with unknown ${c}`);
}

const q = (v: unknown) => (v == null ? "null" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a: readonly unknown[] | undefined, cast: string) => `array[${(a ?? []).map(q).join(", ")}]::${cast}`;

const cols = [
  "id", "city_id", "name", "name_ja", "category", "coords", "nearest_station", "station_walk_min",
  "interest_tags", "energy", "crowd_level", "discovery", "signature", "physical_demand",
  "duration_taste_min", "duration_typical_min", "duration_full_min", "best_window", "crowd_note",
  "worth_it_if", "skip_if", "local_tip", "cost_jpy", "booking_req", "booking_lead_days",
  "opens_at", "closes_at", "closed_weekdays", "conflicts_with", "pairs_with", "seasons", "sources",
  "verification_status",
];

const row = (p: PlaceSeed) => [
  q(p.id), q(p.city), q(p.name), q(p.nameJa), q(p.category),
  `extensions.ST_SetSRID(extensions.ST_MakePoint(${p.lon}, ${p.lat}), 4326)::extensions.geography`,
  q(p.station), q(p.walk),
  arr(p.tags, "interest_tag[]"), q(p.energy), q(p.crowd), q(p.discovery), q(p.signature), q(p.physical ?? null),
  q(p.taste), q(p.typical), q(p.full), arr(p.window, "text[]"), q(p.crowdNote),
  arr(p.worthIf, "text[]"), arr(p.skipIf, "text[]"), q(p.tip), q(p.cost), q(p.booking ?? "none"), q(p.lead ?? null),
  q(p.opens ?? null), q(p.closes ?? null), arr(p.closedWeekdays, "int[]"), arr(p.conflicts, "text[]"), arr(p.pairs, "text[]"),
  arr(p.seasons, "text[]"), arr(p.sources, "text[]"),
  "'draft'",
];

const updates = cols.filter((c) => c !== "id").map((c) => `${c} = excluded.${c}`).join(", ");

const byCity = new Map<string, PlaceSeed[]>();
for (const p of all) (byCity.get(p.city) ?? byCity.set(p.city, []).get(p.city)!).push(p);

const out: string[] = [
  "-- Bento · seed · drafted places for the Kansai–Sanyo corridor",
  "-- Generated by scripts/export-places-seed.ts from src/lib/places/seed/*.ts.",
  "-- Every row is a DRAFT. Judgement fields stay hidden until verified in /admin.",
  "-- Re-applying refreshes drafts only; verified records are never overwritten.",
  "",
];
for (const [city, places] of byCity) {
  out.push(`-- ${city} · ${places.length} records`);
  out.push(`insert into places (${cols.join(", ")}) values`);
  out.push(places.map((p) => `  (${row(p).join(", ")})`).join(",\n"));
  out.push(`on conflict (id) do update set ${updates}\nwhere places.verification_status = 'draft';`);
  out.push("");
}
process.stdout.write(out.join("\n"));
console.error(`${all.length} drafts across ${byCity.size} cities`);
