/**
 * Turns the typed corridor seed into SQL, so the database and the tests
 * route over the same numbers.
 *
 *   npx tsx scripts/export-transit-seed.ts > supabase/seed_transit.sql
 */
import { stations, edges } from "../src/lib/transit/seed/kansai-sanyo";

const q = (v: unknown) =>
  v == null ? "null" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`;
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]::text[]`;

const out: string[] = [
  "-- Bento · seed · transit graph for the Kansai–Sanyo corridor",
  "-- Generated by scripts/export-transit-seed.ts from src/lib/transit/seed/kansai-sanyo.ts.",
  "-- Do not edit by hand; edit the TypeScript and re-export.",
  "",
  "insert into stations (id, name, name_ja, city_id, coords, lines) values",
];
out.push(
  stations
    .map((s) =>
      `  (${q(s.id)}, ${q(s.name)}, ${q(s.nameJa)}, ${q(s.cityId)}, ` +
      (s.lat != null && s.lon != null ? `extensions.ST_SetSRID(extensions.ST_MakePoint(${s.lon}, ${s.lat}), 4326)::extensions.geography` : "null") +
      `, ${arr(s.lines)})`,
    )
    .join(",\n") + "\non conflict (id) do update set name = excluded.name, name_ja = excluded.name_ja, city_id = excluded.city_id, coords = excluded.coords, lines = excluded.lines;",
  "",
  "insert into station_edges (from_station, to_station, line, mode, operator, km, minutes, fare_jpy, stops, note) values",
);
out.push(
  edges
    .map((e) =>
      `  (${q(e.from)}, ${q(e.to)}, ${q(e.line)}, ${q(e.mode)}, ${q(e.operator ?? null)}, ${q(e.km ?? null)}, ${e.minutes}, ${q(e.fareJpy ?? null)}, ${e.stops ?? 1}, ${q(e.note ?? null)})`,
    )
    .join(",\n") + "\non conflict (from_station, to_station, line) do update set mode = excluded.mode, operator = excluded.operator, km = excluded.km, minutes = excluded.minutes, fare_jpy = excluded.fare_jpy, stops = excluded.stops, note = excluded.note;",
  "",
);
process.stdout.write(out.join("\n"));
